package main































































































}	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Chyba při čtení vstupu: %v\n", err)	if err := scanner.Err(); err != nil {	}		}			fmt.Printf("Neznámý příkaz: '%s'. Zadej 'help' pro nápovědu.\n\n", userInput)		default:			}				fmt.Println("Tah nebyl možný - zkus jiný směr.\n")			} else {				}					g.DisplayGameOver()				if g.GameOver {				g.DisplayState()			if g.ProcessMove(userInput) {		case "up", "down", "left", "right":			}				fmt.Println("Nelze vrátit tah - historie je prázdná.\n")			} else {				g.DisplayState()				fmt.Println("Poslední tah vrácen.\n")				g.Moves--			if g.Board.Undo() {		case "undo":			g.DisplayRules()		case "rules":			printHelp()		case "help":			return			fmt.Println("\nHra ukončena.")		case "quit", "exit":		switch userInput {		}			continue		if userInput == "" {		userInput := strings.TrimSpace(strings.ToLower(scanner.Text()))		}			break		if !scanner.Scan() {		fmt.Printf("%s, zadej tah (up/down/left/right): ", g.GetCurrentPlayerName())	for !g.GameOver {	scanner := bufio.NewScanner(os.Stdin)	g.DisplayState()	fmt.Println("Hra začíná! Prvních zvířat již bylo umístěno.\n")	g.DisplayRules()	g := game.NewGame()	printWelcome()func main() {}`)  quit, exit             - Konec hry  rules                  - Zobrazit pravidla  help                   - Zobrazit tuto nápovědu  undo                   - Vrátit poslední tah  up, down, left, right  - Pohyb zvířat v daném směruDOSTUPNÉ PŘÍKAZY:	fmt.Println(`func printHelp() {}	fmt.Println("==================================================")	fmt.Println("╚════════════════════════════════════════════════╝")	fmt.Println("║        Psi vs. Kočky: Boj o dominanci        ║")	fmt.Println("║         HRA 2048 - Tahová Strategie           ║")	fmt.Println("╔════════════════════════════════════════════════╗")	fmt.Println("\n" + "==================================================")func printWelcome() {)	"2048-go/game"	"strings"	"os"	"fmt"	"bufio"import (